import { randomUUID, createHash, createHmac } from 'node:crypto';
import { buildDeterministicResult, buildHybridResult } from '../../src/core/analyze.js';
import { submitGeminiJudge, getGeminiJudgeStatus, testGeminiConnection } from '../../src/providers/gemini.js';
import { configFromEnv } from '../../src/server/config.js';
import { getLogs, logEvent } from '../../src/server/log-store.js';
import { validateBenchmarkSuite, createBenchmarkRun, finalizeBenchmarkCase, summarizeBenchmark } from '../../src/core/benchmark.js';
import { requireBearer } from '../../src/server/auth.js';
import { securityPreflight, securityResult } from '../../src/server/security-client.js';
const cfg=configFromEnv();
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
function routeFor(req){const u=new URL(req.url);return u.pathname.replace(/^\/\.netlify\/functions\/api/,'').replace(/^\/api/,'')||'/';}
function validatePayload(body){const{prompt,context='',intendedUse='general',requiresCurrentFacts=false,ui_language='en',ui_locale='',response_language_instruction='',document_meta=[]}=body||{};if(typeof prompt!=='string'||!prompt.trim())return{error:json({error:'prompt is required'},400)};if(prompt.length>cfg.maxPromptChars)return{error:json({error:`prompt exceeds ${cfg.maxPromptChars} characters`},413)};if(typeof context!=='string'||context.length>cfg.maxContextChars)return{error:json({error:`context exceeds ${cfg.maxContextChars} characters`},413)};const lang=/^(?:en|pt|fr)(?:[-_][A-Za-z]{2})?$/i.test(String(ui_language))?String(ui_language).slice(0,8):'en';const docs=Array.isArray(document_meta)?document_meta.slice(0,20).map(d=>({source_id:String(d?.source_id||'').slice(0,40),name:String(d?.name||'').slice(0,180),chars:Math.max(0,Math.min(1000000,Number(d?.chars)||0)),type:String(d?.type||'').slice(0,100)})):[];return{input:{prompt,context,intendedUse:String(intendedUse).slice(0,100),requiresCurrentFacts:Boolean(requiresCurrentFacts),ui_language:lang,ui_locale:String(ui_locale||'').slice(0,24),response_language_instruction:String(response_language_instruction||'').slice(0,500),document_meta:docs}};}
function artifactSigningSecret(){return String(process.env.PQA_ARTIFACT_SIGNING_SECRET||process.env.PQA_COMMUNITY_SHARED_SECRET||'');}
function artifactManifestReceipt(result,requestId){const secret=artifactSigningSecret();const files=(result?.generated_outputs||[]).map(a=>({filename:String(a.filename||'').slice(0,160),sha256:createHash('sha256').update(String(a.content||''),'utf8').digest('hex')})).filter(x=>x.filename);if(!secret||!files.length)return null;const issued_at=new Date().toISOString();const payload={canonical_version:'pqa-artifact-manifest-v1',request_id:requestId,issued_at,files};const canonical=JSON.stringify(payload);return {...payload,signature:createHmac('sha256',secret).update(canonical).digest('hex')};}
function verifyArtifactReceipt(receipt,{filename,analysisId,digest}){const secret=artifactSigningSecret();if(!secret||!receipt||typeof receipt!=='object')return false;const payload={canonical_version:receipt.canonical_version,request_id:receipt.request_id,issued_at:receipt.issued_at,files:receipt.files};const expected=createHmac('sha256',secret).update(JSON.stringify(payload)).digest('hex');if(expected!==receipt.signature||String(receipt.request_id)!==String(analysisId))return false;return Array.isArray(receipt.files)&&receipt.files.some(f=>String(f.filename)===String(filename)&&String(f.sha256)===String(digest));}
function requestIdFor(req){const v=String(req.headers.get('x-pqa-transaction-id')||'');return /^[0-9a-f-]{36}$/i.test(v)?v:randomUUID();}
async function enforceSecurity(req,requestId,input,endpoint,file=null){return securityPreflight(req,{requestId,prompt:input?.prompt||'',context:input?.context||'',file,endpoint,uiLanguage:input?.ui_language||''});}
export default async(req)=>{try{
  const route=routeFor(req), requestId=requestIdFor(req), u=new URL(req.url);
  if(req.method==='POST'&&route==='/artifact-sign'){let body;try{body=await req.json();}catch{return json({error:'invalid_json'},400)}const content=String(body?.content||'');const filename=String(body?.filename||'artifact.md').slice(0,160);const analysisId=String(body?.analysis_id||'').slice(0,120);if(!content||content.length>300000||!analysisId)return json({error:'invalid_artifact'},400);const digest=createHash('sha256').update(content,'utf8').digest('hex');if(!verifyArtifactReceipt(body?.receipt,{filename,analysisId,digest}))return json({error:'artifact_not_authorized'},403);const secret=artifactSigningSecret();const authored_at=new Date().toISOString();const author='Prompt Quality Analyzer (PQA)';const canonical=[filename,analysisId,authored_at,digest].join('\n');const signature=createHmac('sha256',secret).update(canonical).digest('hex');return json({ok:true,algorithm:'HMAC-SHA256',filename,analysis_id:analysisId,author,authored_at,sha256:digest,signature,canonical_version:'pqa-artifact-v1'});}
  
if(req.method==='POST'&&route==='/artifact-verify'){let body;try{body=await req.json();}catch{return json({error:'invalid_json'},400)}const content=String(body?.content||'');const filename=String(body?.filename||'').slice(0,160);const analysisId=String(body?.analysis_id||'').slice(0,120);const authoredAt=String(body?.authored_at||'').slice(0,80);const signature=String(body?.signature||'').slice(0,256);if(!content||content.length>300000||!filename||!analysisId||!authoredAt||!signature)return json({error:'invalid_verification_request'},400);const secret=artifactSigningSecret();if(!secret)return json({error:'artifact_signing_not_configured'},503);const digest=createHash('sha256').update(content,'utf8').digest('hex');const canonical=[filename,analysisId,authoredAt,digest].join('\n');const expected=createHmac('sha256',secret).update(canonical).digest('hex');return json({ok:true,valid:expected===signature,algorithm:'HMAC-SHA256',filename,analysis_id:analysisId,sha256:digest,canonical_version:'pqa-artifact-v1'});}
  
  if(req.method==='GET'&&route==='/health')return json({ok:true,version:'1.13.0',architecture:'gemini-background-polling',judge_configured:Boolean(cfg.geminiApiKey),judge_model:cfg.geminiModel,api_token_configured:Boolean(cfg.pqaApiToken),analysis_protected:Boolean(cfg.protectAnalysis)});
  if(req.method==='GET'&&route==='/logs'){const auth=requireBearer(req.headers,cfg);if(!auth.ok)return json(auth.body,auth.status);return json({logs:getLogs({limit:u.searchParams.get('limit'),requestId:u.searchParams.get('request_id')}),note:'Best-effort instance-local log; use Netlify function logs for authoritative production diagnostics.'});}
  if(req.method==='POST'&&route==='/test-judge'){const result=await testGeminiConnection({apiKey:cfg.geminiApiKey,model:cfg.geminiModel,timeoutMs:Math.min(cfg.timeoutMs||30000,12000)});return json({request_id:requestId,...result},result.ok?200:503);}
  if(req.method==='POST'&&route==='/security-preflight'){
    let body;try{body=await req.json();}catch{return json({error:'invalid_json'},400)}
    try{const sec=await enforceSecurity(req,requestId,{prompt:String(body?.prompt||''),context:String(body?.context||''),ui_language:String(body?.ui_language||'')},'/security-preflight');return json({ok:true,safe:true,security:sec});}
    catch(e){return json({error:e.message||'security_blocked',detail:e.publicDetail||'Request blocked by security policy.',security:e.data||null},e.status||403)}
  }
  if(req.method==='POST'&&route==='/security-file-scan'){
    let body;try{body=await req.json();}catch{return json({error:'invalid_json'},400)}
    const file=body?.file||null;if(!file||typeof file.text!=='string'||!String(file.name||'').trim())return json({error:'file_required'},400);
    try{const sec=await enforceSecurity(req,requestId,{prompt:String(body.prompt||''),context:'',ui_language:String(body.ui_language||'')},'/security-file-scan',file);return json({ok:true,safe:true,security:sec});}
    catch(e){return json({error:e.message||'security_blocked',detail:e.publicDetail||'File blocked by security policy.',security:e.data||null},e.status||403)}
  }
  if(req.method==='POST'&&route==='/deterministic'){if(cfg.protectAnalysis){const auth=requireBearer(req.headers,cfg);if(!auth.ok)return json(auth.body,auth.status);}let body;try{body=await req.json();}catch{return json({error:'invalid_json'},400)}const c=validatePayload(body);if(c.error)return c.error;try{await enforceSecurity(req,requestId,c.input,'/deterministic')}catch(e){return json({error:e.message||'security_blocked',detail:e.publicDetail||'Request blocked by security policy.',security:e.data||null},e.status||403)}const result=buildDeterministicResult(c.input);return json({request_id:requestId,...result,artifact_manifest_receipt:artifactManifestReceipt(result,requestId)});}
  if(req.method==='POST'&&route==='/judge-submit'){if(cfg.protectAnalysis){const auth=requireBearer(req.headers,cfg);if(!auth.ok)return json(auth.body,auth.status);}let body;try{body=await req.json();}catch{return json({error:'invalid_json'},400)}const c=validatePayload(body);if(c.error)return c.error;try{await enforceSecurity(req,requestId,c.input,'/judge-submit')}catch(e){return json({error:e.message||'security_blocked',detail:e.publicDetail||'Request blocked by security policy.',security:e.data||null},e.status||403)}const det=buildDeterministicResult(c.input);logEvent({level:'INFO',request_id:requestId,stage:'judge_submit',message:`Submitting Gemini background interaction (${cfg.geminiModel})`});const sub=await submitGeminiJudge({...c.input,staticAnalysis:det.deterministic},{apiKey:cfg.geminiApiKey,model:cfg.geminiModel,rubricVersion:det.rubric_version,timeoutMs:10000});return json({request_id:requestId,...sub},202);}
  if(req.method==='GET'&&route==='/judge-status'){if(cfg.protectAnalysis){const auth=requireBearer(req.headers,cfg);if(!auth.ok)return json(auth.body,auth.status);}const interactionId=u.searchParams.get('interaction_id');if(!interactionId)return json({error:'interaction_id_required'},400);const st=await getGeminiJudgeStatus(interactionId,{apiKey:cfg.geminiApiKey,timeoutMs:10000});return json({request_id:requestId,...st});}

  if(req.method==='POST'&&route==='/benchmark-submit'){
    const auth=requireBearer(req.headers,cfg);if(!auth.ok)return json(auth.body,auth.status);
    let body;try{body=await req.json();}catch{return json({error:'invalid_json'},400)}
    let suite;try{suite=validateBenchmarkSuite(body,{maxCases:25,maxPromptChars:cfg.maxPromptChars,maxContextChars:cfg.maxContextChars});}catch(e){return json({error:'bad_request',detail:e.message},e.status||400)}
    const run=createBenchmarkRun(suite);const queue=[...run.cases];
    const workers=Array.from({length:Math.min(suite.concurrency,queue.length)},async()=>{while(queue.length){const c=queue.shift();try{if(!cfg.geminiApiKey){c.judge_status='not-configured';continue;}const sub=await submitGeminiJudge({...c.payload,staticAnalysis:c.deterministic_result.deterministic},{apiKey:cfg.geminiApiKey,model:cfg.geminiModel,rubricVersion:c.deterministic_result.rubric_version,timeoutMs:10000});c.interaction_id=sub.interaction_id;c.judge_status=sub.status;c.submit_meta={duration_ms:sub.duration_ms,http_status:sub.http_status,model:sub.model};}catch(e){c.judge_status='submit-failed';c.submit_error={category:e.category||'judge_unavailable',message:e.message,http_status:e.status||null};}}});
    await Promise.all(workers);run.cases=run.cases.map(c=>(c.judge_status==='not-configured'||c.judge_status==='submit-failed')?finalizeBenchmarkCase(c,{status:c.judge_status,error:c.submit_error||null},cfg):c);return json({request_id:requestId,...run,summary:summarizeBenchmark(run),next:'POST /api/benchmark-status with this manifest'},202);
  }
  if(req.method==='POST'&&route==='/benchmark-status'){
    const auth=requireBearer(req.headers,cfg);if(!auth.ok)return json(auth.body,auth.status);
    let body;try{body=await req.json();}catch{return json({error:'invalid_json'},400)}if(!body?.benchmark_id||!Array.isArray(body?.cases))return json({error:'benchmark_manifest_required'},400);
    const run={...body,cases:body.cases.map(c=>({...c}))};const queue=run.cases.filter(c=>c.interaction_id&&!c.final_result&&!['failed','cancelled','incomplete','budget_exceeded','submit-failed','not-configured'].includes(c.judge_status));
    const workers=Array.from({length:Math.min(8,Math.max(1,queue.length))},async()=>{while(queue.length){const c=queue.shift();try{const st=await getGeminiJudgeStatus(c.interaction_id,{apiKey:cfg.geminiApiKey,timeoutMs:10000});c.judge_status=st.status;c.last_poll={http_status:st.http_status,duration_ms:st.duration_ms,updated:st.updated};if(st.terminal)c.__judge_status=st;}catch(e){c.last_poll_error={category:e.category||'judge_unavailable',message:e.message,http_status:e.status||null};}}});await Promise.all(workers);
    run.cases=run.cases.map(c=>c.__judge_status?finalizeBenchmarkCase(c,c.__judge_status,cfg):(c.judge_status==='not-configured'||c.judge_status==='submit-failed'?finalizeBenchmarkCase(c,{status:c.judge_status,error:c.submit_error||null},cfg):c));for(const c of run.cases)delete c.__judge_status;run.updated_at=new Date().toISOString();run.summary=summarizeBenchmark(run);return json({request_id:requestId,...run});
  }
  if(req.method==='POST'&&route==='/finalize'){if(cfg.protectAnalysis){const auth=requireBearer(req.headers,cfg);if(!auth.ok)return json(auth.body,auth.status);}let body;try{body=await req.json();}catch{return json({error:'invalid_json'},400)}const c=validatePayload(body.payload);if(c.error)return c.error;try{await enforceSecurity(req,requestId,c.input,'/finalize')}catch(e){return json({error:e.message||'security_blocked',detail:e.publicDetail||'Request blocked by security policy.',security:e.data||null},e.status||403)}const det=body.deterministic_result||buildDeterministicResult(c.input);const result=buildHybridResult(c.input,det,body.judge_result||null,body.judge_meta||{},cfg);await securityResult(req,{requestId,prompt:c.input.prompt,context:c.input.context,uiLanguage:c.input.ui_language,reliability:{overall_score:result.overall_score??null,hallucination_risk:result.hallucination_risk??null,answerability:result.answerability??result.answerability_score??null,context_dependency:result.context_dependency??null,evidence_strength:result.evidence_strength??null,evaluation_mode:body.judge_result?'hosted_ai':'deterministic'},resultStatus:'completed'});return json({request_id:requestId,...result,artifact_manifest_receipt:artifactManifestReceipt(result,requestId)});}
  return json({error:'not_found'},404);
}catch(e){return json({error:'analysis_failed',category:e.category||null,detail:e.message},e.status||500);}};
