const RX = {
  current:/\b(today|current|currently|latest|recent|this week|this month|as of|now|202[5-9]|hoje|atual|atualmente|mais recente|últim[oa]s?|esta semana|este mês|agora|aujourd'hui|actuel|actuelle|actuellement|récent|récente|derni(?:er|ère)|cette semaine|ce mois|maintenant)\b/i,
  citation:/\b(cite|citation|source|reference|references|evidence|supporting section|supporting quote|citar|citação|fonte|fontes|referência|referências|evidência|trecho de apoio|citation|source|sources|référence|références|preuve|preuves)\b/i,
  ground:/\b(only (use|using)|use only|provided context|supplied (document|documents|code|data|policy)|retrieved|verified|approved sources?|authoritative|primary sources?|ground(ed|ing)|evidence|do not (infer|invent|fabricate|assume)|without evidence|use apenas|usar apenas|somente (use|usar)|contexto fornecido|documentos? fornecid[oa]s?|dados fornecidos|fontes? verificad[oa]s?|fontes? autorizad[oa]s?|fontes? primárias?|evidência|não (inferir|invente|inventar|fabricar|assumir)|sem evidência|utilisez seulement|n'utilisez que|contexte fourni|documents? fournis?|données fournies|sources? vérifiées?|sources? autorisées?|sources? primaires?|preuves?|ne (déduisez|inventez|fabriquez|supposez) pas|sans preuve)\b/i,
  format:/\b(json|yaml|table|bullet|bullets|schema|format|return|respond with|output|sections?|fields?|severity|confidence|tabela|lista|formato|retorne|responda com|saída|seções?|campos?|severidade|confiança|tableau|liste|format|retournez|répondez avec|sortie|sections?|champs?|sévérité|confiance)\b/i,
  tool:/\b(tool|tools|search|retrieve|retrieval|database|function|browse|tracking|lookup|ferramenta|ferramentas|buscar|busque|pesquisar|pesquise|recuperar|recupere|banco de dados|função|navegar|navegue|consultar|consulte|outil|outils|rechercher|recherchez|récupérer|récupérez|base de données|fonction|parcourir|parcourez|consulter|consultez)\b/i,
  boundedTool:/\b(reuse|avoid repeated|do not repeat|minimum.*tools?|only when needed|stop after|failed attempts?|do not call.*already|reuse prior|reutiliz|evite repetir|não repita|mínim[oa].*ferrament|somente quando necessário|pare após|tentativas? falhas?|não chame.*já|réutilis|évitez de répéter|ne répétez pas|minim.*outils?|seulement si nécessaire|arrêtez après|tentatives? échouées?)\b/i,
  certainty:/\b(always answer|always respond|never say (you )?(don't|do not) know|definitive answer|must answer|do not refuse|never mention uncertainty|be completely certain|always be certain|sempre responda|responda sempre|nunca diga (que )?(você )?não sabe|resposta definitiva|deve responder|não recuse|nunca mencione (a )?incerteza|seja completamente cert[oa]|sempre tenha certeza|répondez toujours|toujours répondre|ne dites jamais (que )?vous ne savez pas|réponse définitive|devez répondre|ne refusez pas|ne mentionnez jamais l'incertitude|soyez totalement certain)\b/i,
  infer:/\b(fill(?: in)?[^.]{0,25}missing|guess|make reasonable (assumptions|guesses)|infer[^.]{0,25}(likely|missing)|estimate.*anyway|assume whatever|reconstruct unreadable|choose.*seems (right|likely|plausible)|invent realistic|preencha[^.]{0,25}(faltante|ausente)|adivinhe|adivinhando|adivinhar|faça suposições|inferir?[^.]{0,25}(provável|faltante|ausente)|estime.*mesmo assim|assuma qualquer|reconstru[aí].*ilegível|escolha.*parece (certo|provável|plausível)|invente.*realista|remplissez?[^.]{0,25}(manquant|absent)|devinez|devinant|deviner|faites? des suppositions|dédui(?:re|sez)[^.]{0,25}(probable|manquant)|estimez.*quand même|supposez n'importe|reconstituez.*illisible|choisissez.*semble (correct|probable|plausible)|inventez.*réaliste)\b/i,
  noGuess:/\b((do not|don't|never) (guess|infer|invent|fabricate|assume)|without (guessing|inferring)|null for missing|leave .*null|não (adivinhe|adivinhar|infira|inferir|invente|inventar|fabrique|fabricar|assuma|assumir)|sem (adivinhar|inferir)|null (?:para|nos?) (?:os )?(?:dados |campos )?(faltantes|ausentes)|deixe .*null|ne (devinez|déduisez|inventez|fabriquez|supposez) pas|sans (deviner|déduire)|null (?:pour|dans) (?:les )?(?:données |champs )?(manquants?|manquantes?|absents?|absentes?)|laissez .*null)\b/i,
  repeatedTool:/\b((call|use).{0,20}(tool|search).{0,30}(three|3|multiple) times|every question.{0,30}tool|(chame|use).{0,20}(ferramenta|busca).{0,30}(três|3|múltiplas) vezes|cada pergunta.{0,30}ferramenta|(appelez|utilisez).{0,20}(outil|recherche).{0,30}(trois|3|plusieurs) fois|chaque question.{0,30}outil)\b/i,
  endlessTool:/\b(keep calling|never stop|until you get an answer|continue chamando|nunca pare|até obter uma resposta|continuez à appeler|n'arrêtez jamais|jusqu'à obtenir une réponse)\b/i,
  impossibleConstraint:/\b((comprehensive|exhaustive|every possible|every important|abrangente|exaustiv[oa]|todas? as possibilidades|tudo importante|complet|exhaustif|toutes? les possibilités).{0,80}(under|exactly|menos de|exatamente|moins de|exactement).{0,20}(\d+)\s*(word|words|palavra|palavras|mot|mots)|(under|exactly|menos de|exatamente|moins de|exactement).{0,20}(\d+)\s*(word|words|palavra|palavras|mot|mots).{0,80}(comprehensive|exhaustive|abrangente|exaustiv|complet|exhaustif))\b/i,
  intentionalRepeat:/\b(repeat (all|the).{0,30}(context|information)|extremely verbose|repita (todo|o).{0,30}(contexto|informação)|extremamente detalhado|répétez (tout|le).{0,30}(contexte|information)|extrêmement verbeux)\b/i,
  destructive:/\b((delete|remove|overwrite|destroy|excluir|remover|sobrescrever|destruir|supprimer|effacer|écraser|détruire).{0,80}(without confirmation|do not ask|automatically|sem confirmação|não pergunte|automaticamente|sans confirmation|ne demandez pas|automatiquement))\b/i,
  safeDestructive:/\b(require explicit confirmation|before.*destructive|read-only diagnostics|irreversible.*confirmation|exija confirmação explícita|antes.*destrutiv|diagnóstico somente leitura|irreversível.*confirmação|exigez une confirmation explicite|avant.*destruct|diagnostic en lecture seule|irréversible.*confirmation)\b/i,
  causalOverclaim:/\b(prove[^.]{0,40}caus\w*|caused[^.]{0,40}correlation|correlation[^.]{0,40}proves?|prove[^.]{0,40}caus|correla[cç][aã]o[^.]{0,40}prova|causou[^.]{0,40}correla[cç][aã]o|prouve[^.]{0,40}caus|corrélation[^.]{0,40}prouve|causé[^.]{0,40}corrélation)\b/i,
  causalSafe:/\b(distinguish correlation from causation|confounders?|causal claim|additional evidence required|diferencie correla[cç][aã]o de causalidade|fatores de confusão|alegação causal|evidência adicional necessária|distinguez corrélation et causalité|facteurs de confusion|affirmation causale|preuves supplémentaires requises)\b/i,
  nullMissing:/\b((return|null|leave|retorne|deixe|retournez|laissez).{0,20}(missing|unavailable|unreadable|faltante|ausente|indisponível|ilegível|manquant|absent|indisponible|illisible)|null.{0,20}(missing|faltante|ausente|manquant|absent))\b/i,
  conflictSafe:/\b((report|surface|show|state|identify|highlight|relate|mostre|declare|identifique|destaque|signalez|montrez|indiquez|identifiez|soulignez).{0,35}(the )?(conflict|disagreement|conflito|divergência|conflit|désaccord)|do not reconcile|não reconcilie|ne réconciliez pas|mark.*ambiguous|marque.*ambígu|marquez.*ambigu|all candidates|todos os candidatos|tous les candidats)\b/i,
  conflictBad:/\b(((if|when|se|quando|si|lorsque).{0,30}(sources?|documents?|evidence|values?|fontes?|documentos?|evidências?|valores?|sources?|documents?|preuves?|valeurs?).{0,30}(conflict|disagree|conflit|diverg|discord).{0,100}(choose|pick|select|use|escolha|selecione|use|choisissez|sélectionnez|utilisez).{0,60}(likely|plausible|best|most likely|provável|plausível|melhor|mais provável|probable|plausible|meilleur|plus probable)|silently.{0,60}(choose|pick|resolve)|silenciosamente.{0,60}(escolha|resolva)|silencieusement.{0,60}(choisissez|résolvez)|choose.*seems (right|likely|plausible)|escolha.*parece (certo|provável|plausível)|choisissez.*semble (correct|probable|plausible)))\b/i,
  uncertaintySuppression:/\b((hide|mask|suppress|omit|never mention|do not mention|don't mention|oculte|esconda|mascare|suprima|omita|nunca mencione|não mencione|cachez|masquez|supprimez|omettez|ne mentionnez jamais|ne mentionnez pas).{0,45}(uncertainty|limitations?|confidence|caveats?|incerteza|limita[cç][oõ]es|confian[cç]a|ressalvas?|incertitude|limitations?|confiance|réserves?)|sound authoritative.{0,50}(regardless|even if)|pare[cç]a autorit[aá]rio.{0,50}(independentemente|mesmo se)|semblez autoritaire.{0,50}(quoi qu'il arrive|même si)|never (express|show|state).{0,30}(uncertainty|doubt)|nunca (expresse|mostre|declare).{0,30}(incerteza|d[uú]vida)|ne (exprimez|montrez|indiquez) jamais.{0,30}(incertitude|doute))\b/i,
  fabricateCitation:/\b((invent|fabricate|make up|create|invente|fabrique|crie|inventez|fabriquez|créez).{0,35}(citation|source|paper|reference|url|cita[cç][aã]o|fonte|artigo|refer[eê]ncia|citation|source|article|référence)|if.{0,25}(citation|source|url).{0,25}(missing|unknown).{0,35}(guess|invent|infer)|se.{0,25}(cita[cç][aã]o|fonte|url).{0,25}(faltante|desconhecid).{0,35}(adivinhe|invente|infira)|si.{0,25}(citation|source|url).{0,25}(manquante|inconnue).{0,35}(devinez|inventez|déduisez))\b/i,
  currentRetrieval:/\b((search|browse|retrieve|look up|query|buscar|busque|pesquisar|pesquise|recuperar|recupere|consultar|consulte|rechercher|recherchez|parcourir|parcourez|récupérer|récupérez|consulter|consultez).{0,45}(current|latest|recent|authoritative|official|primary|sources?|reports?|atual|mais recente|autorizad|oficial|prim[aá]ri|fontes?|relat[oó]rios?|actuel|récent|autorisé|officiel|primaire|sources?|rapports?)|(current|latest|recent|atual|mais recente|actuel|récent).{0,45}(search|browse|retrieve|authoritative|official|primary sources?|buscar|pesquisar|recuperar|fontes? oficiais|fontes? prim[aá]rias|rechercher|parcourir|récupérer|sources? officielles|sources? primaires))\b/i,
  judgeOverride:/\b((ignore|bypass|override|disregard|ignore|contorne|substitua|desconsidere|ignorez|contournez|remplacez).{0,50}(evaluator|judge|rubric|scoring|system instructions?|avaliador|juiz|rubrica|pontua[cç][aã]o|instru[cç][oõ]es do sistema|évaluateur|juge|barème|notation|instructions système)|(?:give|assign|return|d[eê]|atribua|retorne|donnez|attribuez|retournez).{0,30}(100\/100|score of 100|low risk|pontua[cç][aã]o 100|risco baixo|note de 100|risque faible).{0,40}(regardless|no matter|without evaluating|independentemente|sem avaliar|quoi qu'il arrive|sans évaluer))\b/i,
  systemPromptExtraction:/\b((reveal|print|show|repeat|extract|revele|imprima|mostre|repita|extraia|révélez|imprimez|montrez|répétez|extrayez).{0,40}(system prompt|hidden instructions?|evaluator instructions?|rubric|prompt do sistema|instru[cç][oõ]es ocultas?|instru[cç][oõ]es do avaliador|rubrica|prompt système|instructions cachées?|instructions de l'évaluateur|barème))\b/i,
  roleOverride:/\b((you are now|act as|agora você é|atue como|vous êtes maintenant|agissez comme).{0,40}(the evaluator|system|judge|avaliador|sistema|juiz|évaluateur|système|juge)|ignore previous instructions?|ignore as instru[cç][oõ]es anteriores|ignorez les instructions précédentes)\b/i,
  templateToken:/\{\{[^}]{1,80}\}\}|\$\{[^}]{1,80}\}|\[[A-Z][A-Z0-9 _-]{2,60}\]|<([a-z][a-z0-9_-]{2,40})>/i,
};

const ABSTAIN = {
  forbid:/((never|do not|don't).{0,30}(say|state|admit|mention|express).{0,35}(don't know|do not know|uncertain|uncertainty|not sure|cannot verify|limitations?)|(nunca|não).{0,30}(diga|declare|admita|mencione|expresse).{0,35}(não sabe|incerteza|não tem certeza|não pode verificar|limita[cç][oõ]es?)|(ne|n').{0,20}(dites|indiquez|admettez|mentionnez|exprimez).{0,35}(jamais|pas).{0,20}(ne savez|incert|pas sûr|vérifier|limitations?))/i,
  allow:/((if|when).{0,40}(insufficient|missing|uncertain|cannot verify|don't know|do not know|not sure).{0,55}(say|state|report|identify|explain|admit)|(state|report|identify|explain).{0,35}(what is missing|uncertainty|insufficient evidence|cannot verify)|(se|quando).{0,40}(insuficiente|faltante|ausente|incerto|não puder verificar|não sabe|não tiver certeza).{0,55}(diga|declare|informe|identifique|explique|admita)|(diga|declare|informe|identifique|explique).{0,35}(o que falta|incerteza|evidência insuficiente|não pode verificar)|(si|lorsque).{0,40}(insuffisant|manquant|incertain|ne peut pas vérifier|ne savez pas|pas sûr).{0,55}(dites|indiquez|signalez|identifiez|expliquez|admettez)|(dites|indiquez|signalez|identifiez|expliquez).{0,35}(ce qui manque|incertitude|preuves insuffisantes|ne peut pas vérifier))/i,
  safeTerm:/\b(insufficient evidence|evidence is insufficient|cannot verify|unverified|state what is missing|missing information|evidência insuficiente|não pode verificar|não verificad[oa]|informe o que falta|informação faltante|preuves insuffisantes|ne peut pas vérifier|non vérifié|indiquez ce qui manque|information manquante)\b/i
};

const QUALITY_RX = {
  task:/\b(analy[sz]e|assess|evaluate|review|create|build|write|design|implement|develop|generate|explain|compare|summarize|classify|extract|debug|fix|refactor|translate|draft|recommend|calculate|list|return|produce|plan|identify|answer|search|browse|retrieve|analisar|analise|avaliar|avalie|revisar|revise|criar|crie|construir|construa|escrever|escreva|projetar|projete|implementar|implemente|desenvolver|desenvolva|gerar|gere|explicar|explique|comparar|compare|resumir|resuma|classificar|classifique|extrair|extraia|corrigir|corrija|refatorar|refatore|traduzir|traduza|redigir|redija|recomendar|recomende|calcular|calcule|listar|liste|retornar|retorne|produzir|produza|planejar|planeje|identificar|identifique|responder|responda|buscar|busque|pesquisar|pesquise|recuperar|recupere|analyser|analysez|évaluer|évaluez|examiner|examinez|créer|créez|construire|construisez|écrire|écrivez|concevoir|concevez|implémenter|implémentez|développer|développez|générer|générez|expliquer|expliquez|comparer|comparez|résumer|résumez|classifier|classifiez|extraire|extrayez|corriger|corrigez|refactoriser|refactorisez|traduire|traduisez|rédiger|rédigez|recommander|recommandez|calculer|calculez|lister|listez|retourner|retournez|produire|produisez|planifier|planifiez|identifier|identifiez|répondre|répondez|rechercher|recherchez|parcourir|parcourez|récupérer|récupérez)\b/i,
  subject:/\b(api|code|software|system|application|app|service|database|data|document|policy|company|business|customer|user|prompt|instruction|report|analysis|email|market|product|project|evidence|evidences|source|sources|invoice|logs|values|market|registration|empresa|evidência|evidências|fonte|fontes|fatura|logs|valores|mercado|cadastro|negócio|cliente|usuário|dados|documento|política|sistema|aplicação|serviço|instrução|relatório|análise|mercado|produto|projeto|entreprise|client|utilisateur|données|document|politique|système|application|service|instruction|rapport|analyse|marché|produit|projet)\b/i,
  context:/\b(for|using|given|based on|according to|we are|our |company called|environment|stack|version|audience|supplied|provided|attached|following|below|para|usando|dado|com base|de acordo|nossa |empresa chamada|ambiente|versão|público|fornecido|fornecida|anexado|anexada|seguinte|abaixo|pour|avec|étant donné|sur la base|selon|notre |entreprise appelée|environnement|version|public|fourni|fournie|joint|jointe|suivant|ci-dessous)\b/i,
  constraint:/\b(must|should|do not|don't|never|only|without|at least|at most|max(?:imum)?|min(?:imum)?|exactly|limit|within|preserve|avoid|deve|deverá|não|nunca|não adivinhe|apenas|somente|sem |pelo menos|no máximo|exatamente|limite|preservar|evitar|doit|devrait|ne pas|ne devinez pas|jamais|seulement|sans |au moins|au plus|exactement|limite|préserver|éviter)\b/i,
  success:/\b(success|acceptance|criteria|requirement|expected result|kpi|pass(?:es|ing)?|validate|verify|testable|sucesso|aceitação|critério|requisito|resultado esperado|validar|verificar|testável|succès|acceptation|critère|exigence|résultat attendu|valider|vérifier|testable)\b/i,
  audience:/\b(act as|you are|for (?:a|an|the) [a-z]|audience|reader|stakeholder|developer|engineer|executive|atue como|você é|para (?:um|uma|o|a) |público|leitor|desenvolvedor|engenheiro|executivo|agis comme|vous êtes|pour (?:un|une|le|la) |public|lecteur|développeur|ingénieur|dirigeant)\b/i
};

function test(rx,text){rx.lastIndex=0;return rx.test(text);}
function duplicateRatio(text){const lines=String(text||'').split(/\n+/).map(x=>x.trim().toLowerCase()).filter(x=>x.length>20);if(!lines.length)return 0;return 1-new Set(lines).size/lines.length;}
function detectLanguage(text=''){
  const s=` ${String(text).toLowerCase()} `;
  const pt=(s.match(/\b(não|nunca|sempre|você|responda|analise|preencha|pesquise|extraia|compare|evidência|evidências|fonte|fontes|dados|valores|ausentes|deve|para|com|uma|um|que)\b/g)||[]).length;
  const fr=(s.match(/\b(ne|pas|jamais|toujours|vous|répondez|analysez|remplissez|recherchez|extrayez|comparez|preuve|preuves|source|sources|données|valeurs|manquantes|doit|pour|avec|une|un|que)\b/g)||[]).length;
  return pt>fr&&pt>=2?'pt':fr>pt&&fr>=2?'fr':'en';
}
function intendedProfile(s='general',prompt=''){
  s=String(s).toLowerCase();const p=String(prompt).toLowerCase();
  if(s.includes('rag')||s.includes('document'))return'rag';if(s.includes('coding')||s.includes('software')||s.includes('código'))return'coding';if(s.includes('research')||s.includes('pesquisa')||s.includes('recherche'))return'research';if(s.includes('agent')||s.includes('tool use')||s.includes('ferrament')||s.includes('outil'))return'agent';if(s.includes('extract')||s.includes('extração')||s.includes('extraction'))return'extraction';if(s.includes('customer')||s.includes('support')||s.includes('suporte')||s.includes('assistance'))return'support';if(s.includes('data')||s.includes('dados')||s.includes('données'))return'data';
  if(/document|attached|supplied context|documento|anexad|contexte fourni/.test(p))return'rag';if(/node\.js|code|código|function|função|fonction|api/.test(p))return'coding';if(/tool|search|retrieve|ferrament|buscar|pesquisar|outil|rechercher|récupérer/.test(p))return'agent';if(/invoice|extract|fields|json only|fatura|extrair|campos|facture|extraire|champs/.test(p))return'extraction';if(/correlation|causation|dataset|forecast|correla[cç][aã]o|causalidade|previs[aã]o|corrélation|causalité|prévision/.test(p))return'data';if(/current|latest|authoritative sources?|market data|tax|atual|mais recente|fontes? autorizad|mercado|imposto|actuel|récent|sources? autorisées|marché|impôt/.test(p))return'research';return'general';
}
function qualityEvidence(prompt,context,hasFormat,hasCitation){
  const p=String(prompt||'').trim(),words=p.split(/\s+/).filter(Boolean);
  const task=test(QUALITY_RX.task,p),subject=test(QUALITY_RX.subject,p)||(task&&words.length>=5),contextProvided=String(context||'').trim().length>0||test(QUALITY_RX.context,p)||p.length>=140;
  const constraints=test(QUALITY_RX.constraint,p),success=test(QUALITY_RX.success,p),audience=test(QUALITY_RX.audience,p),output=Boolean(hasFormat||hasCitation);
  const missing=[];if(!task)missing.push('task');if(!subject)missing.push('subject');if(!contextProvided&&!constraints&&p.length<90)missing.push('context_or_constraints');if(!output)missing.push('output_contract');
  return {task,subject,context:contextProvided,constraints,success,audience,output,positive_count:[task,subject,contextProvided,constraints,success,audience,output].filter(Boolean).length,missing_core:missing,word_count:words.length};
}
function abstentionIntent(p){
  const forbidden=test(ABSTAIN.forbid,p)||test(RX.certainty,p)||test(RX.uncertaintySuppression,p);
  const positive=test(ABSTAIN.allow,p)||(!forbidden&&test(ABSTAIN.safeTerm,p));
  return {positive,forbidden};
}
function dangerousClause(clause){
  if(!clause.trim())return false;
  const noGuess=test(RX.noGuess,clause),safeDestructive=test(RX.safeDestructive,clause),causalSafe=test(RX.causalSafe,clause),conflictSafe=test(RX.conflictSafe,clause);
  return test(RX.certainty,clause)||test(ABSTAIN.forbid,clause)||test(RX.uncertaintySuppression,clause)||test(RX.fabricateCitation,clause)||(test(RX.infer,clause)&&!noGuess)||(test(RX.destructive,clause)&&!safeDestructive)||(test(RX.causalOverclaim,clause)&&!causalSafe)||(test(RX.conflictBad,clause)&&!conflictSafe)||test(RX.repeatedTool,clause)||test(RX.endlessTool,clause)||test(RX.judgeOverride,clause)||test(RX.systemPromptExtraction,clause)||test(RX.roleOverride,clause);
}
function safeBasePrompt(prompt){
  const parts=String(prompt||'').split(/(?<=[.!?])\s+|[;\n]+|\s*,\s*(?=(?:never|always|do not|don't|nunca|sempre|não|jamais|toujours|ne\s))/i).map(x=>x.trim()).filter(Boolean);
  const safe=parts.filter(x=>!dangerousClause(x));
  return safe.join('\n').trim();
}
const REWRITE_TEXT={
  en:{base:'Complete the requested task using only supported information and the reliability requirements below.',title:'Reliability requirements:',missing:'If essential context is missing, identify exactly what is missing before drawing conclusions.',abstain:'If evidence is insufficient or cannot be verified, state the uncertainty and what additional information is needed; do not guess or fabricate.',ground:'Base factual claims only on supplied evidence or explicitly retrieved authoritative sources.',current:'For current facts, retrieve authoritative up-to-date sources and identify the source/date.',cite:'Use only verifiable citations or references; never invent a source, paper, URL, or quotation.',conflict:'If sources or requirements conflict, surface the conflict and do not silently choose an unsupported answer.',tools:'Use only necessary tool calls, reuse valid results, and stop after bounded failures.',destructive:'Require explicit confirmation before destructive or irreversible actions.',causal:'Distinguish correlation from causation and state what additional evidence would be required for a causal claim.',format:'Return a concise answer with clearly separated findings, evidence/assumptions, uncertainty/limitations, and next steps when relevant.'},
  pt:{base:'Execute a tarefa solicitada usando apenas informações sustentadas e os requisitos de confiabilidade abaixo.',title:'Requisitos de confiabilidade:',missing:'Se faltar contexto essencial, identifique exatamente o que está faltando antes de tirar conclusões.',abstain:'Se a evidência for insuficiente ou não puder ser verificada, declare a incerteza e o que é necessário para concluir; não adivinhe nem invente.',ground:'Baseie afirmações factuais apenas nas evidências fornecidas ou em fontes autorizadas explicitamente recuperadas.',current:'Para fatos atuais, consulte fontes autorizadas e atualizadas e identifique a fonte e a data.',cite:'Use apenas citações ou referências verificáveis; nunca invente fonte, artigo, URL ou citação.',conflict:'Se fontes ou requisitos entrarem em conflito, exponha o conflito e não escolha silenciosamente uma resposta sem suporte.',tools:'Use somente as chamadas de ferramenta necessárias, reutilize resultados válidos e pare após falhas limitadas.',destructive:'Exija confirmação explícita antes de ações destrutivas ou irreversíveis.',causal:'Diferencie correlação de causalidade e indique quais evidências adicionais seriam necessárias para uma conclusão causal.',format:'Retorne uma resposta concisa com achados, evidências/suposições, incertezas/limitações e próximos passos quando aplicável.'},
  fr:{base:'Exécutez la tâche demandée uniquement à partir d’informations étayées et des exigences de fiabilité ci-dessous.',title:'Exigences de fiabilité :',missing:'Si un contexte essentiel manque, indiquez précisément ce qui manque avant de tirer des conclusions.',abstain:"Si les preuves sont insuffisantes ou invérifiables, indiquez l'incertitude et les informations nécessaires ; ne devinez pas et n'inventez rien.",ground:'Fondez les affirmations factuelles uniquement sur les preuves fournies ou sur des sources autorisées explicitement récupérées.',current:'Pour les faits actuels, consultez des sources autorisées et à jour et indiquez la source et la date.',cite:"Utilisez uniquement des citations ou références vérifiables ; n'inventez jamais de source, article, URL ou citation.",conflict:'Si des sources ou exigences sont en conflit, signalez le conflit et ne choisissez pas silencieusement une réponse non étayée.',tools:"Utilisez uniquement les appels d'outils nécessaires, réutilisez les résultats valides et arrêtez-vous après un nombre limité d'échecs.",destructive:'Exigez une confirmation explicite avant toute action destructive ou irréversible.',causal:'Distinguez corrélation et causalité et indiquez quelles preuves supplémentaires seraient nécessaires pour une conclusion causale.',format:'Retournez une réponse concise avec résultats, preuves/hypothèses, incertitudes/limites et prochaines étapes lorsque pertinent.'}
};
export function deterministicRewrite(input,analysis){
  const prompt=String(input?.prompt||'').trim();if(!prompt)return null;
  const lang=analysis?.detected_language||detectLanguage(prompt),t=REWRITE_TEXT[lang]||REWRITE_TEXT.en,base=safeBasePrompt(prompt)||t.base;
  const f=analysis?.flags||{},q=analysis?.quality_evidence||{},p=analysis?.profile||'general',items=[];
  if(!q.context||!q.subject)items.push(t.missing);
  if(f.forced||f.abstentionForbidden||f.uncertaintySuppression||f.inferMissing||['rag','research','support','agent','data'].includes(p))items.push(t.abstain);
  if((['rag','research','support'].includes(p)||f.current)&&!f.hasGround)items.push(t.ground);
  if(f.current)items.push(t.current);
  if(f.fabricateCitation||((p==='rag'||String(input?.context||'').length>0)&&!f.hasCitation))items.push(t.cite);
  if(f.conflictBad||f.impossibleConstraint)items.push(t.conflict);
  if((p==='agent'||f.current)&&(f.hasTool||!f.boundedTool))items.push(t.tools);
  if(f.destructive&&!f.safeDestructive)items.push(t.destructive);
  if(f.causalOverclaim&&!f.causalSafe)items.push(t.causal);
  if(!f.hasFormat)items.push(t.format);
  const unique=[...new Set(items)];
  return unique.length?`${base}\n\n${t.title}\n${unique.map(x=>`- ${x}`).join('\n')}`:base;
}

export function deterministicAnalyze({prompt,context='',intendedUse='general',requiresCurrentFacts=false,evaluationMode='auto'}){
  const issues=[],recommendations=[],signals=[],protective=[];
  const p=String(prompt||'').trim(),all=`${p}\n${context}`,dup=duplicateRatio(all),profile=intendedProfile(intendedUse,p),detectedLanguage=detectLanguage(p);
  const current=Boolean(requiresCurrentFacts)||test(RX.current,p),templateDetected=test(RX.templateToken,p),resolvedEvaluationMode=evaluationMode==='template'||(evaluationMode==='auto'&&templateDetected)?'template':'instantiated';
  const currentRetrieval=test(RX.currentRetrieval,p),intent=abstentionIntent(p);
  const hasGround=test(RX.ground,p),hasAbstain=intent.positive,hasCitation=test(RX.citation,p),hasFormat=test(RX.format,p),hasTool=test(RX.tool,p),boundedTool=test(RX.boundedTool,p);
  const quality=qualityEvidence(p,context,hasFormat,hasCitation);
  const forced=test(RX.certainty,p)||intent.forbidden,abstentionForbidden=intent.forbidden,noGuess=test(RX.noGuess,p),inferMissing=test(RX.infer,p)&&!noGuess,destructive=test(RX.destructive,p),safeDestructive=test(RX.safeDestructive,p),causalOverclaim=test(RX.causalOverclaim,p),causalSafe=test(RX.causalSafe,p),nullMissing=test(RX.nullMissing,p),conflictSafe=test(RX.conflictSafe,p),conflictBad=test(RX.conflictBad,p),repeatedTool=test(RX.repeatedTool,p),endlessTool=test(RX.endlessTool,p),impossibleConstraint=test(RX.impossibleConstraint,p),intentionalRepeat=test(RX.intentionalRepeat,p),uncertaintySuppression=test(RX.uncertaintySuppression,p)||abstentionForbidden,fabricateCitation=test(RX.fabricateCitation,p),judgeOverride=test(RX.judgeOverride,p),systemPromptExtraction=test(RX.systemPromptExtraction,p),roleOverride=test(RX.roleOverride,p);

  if(p.length<25){issues.push('The prompt is very short and may underspecify the task.');recommendations.push('State the task, relevant constraints, and expected output explicitly.');}
  if(!quality.task){issues.push('The instruction does not state a clear action for the model to perform.');recommendations.push('Start with a specific action such as analyze, create, compare, review, or extract.');}
  if(!quality.subject){issues.push('The subject or scope of the requested work is not sufficiently defined.');recommendations.push('Name the object, system, document, data, or decision the model should work on.');}
  if(!quality.context&&!quality.constraints&&p.length<90){issues.push('The instruction provides little context or operating constraints.');recommendations.push('Add the minimum context, constraints, audience, or boundaries needed to produce the intended result.');}
  if(current&&!currentRetrieval&&!hasTool&&!hasGround){issues.push('Time-sensitive facts are requested without a retrieval or grounding requirement.');recommendations.push('Require current retrieval/search or provide authoritative current context.');signals.push('time-sensitive-without-grounding');}
  const factual=/\b(fact|policy|law|regulation|research|document|contract|medical|financial|tax|refund|tracking|current|latest|fato|pol[ií]tica|lei|regulamento|pesquisa|documento|contrato|m[eé]dic|financeir|imposto|reembolso|rastreamento|atual|fait|politique|loi|règlement|recherche|document|contrat|médical|financier|impôt|remboursement|actuel)\b/i.test(all);
  const missingDocSafe=profile==='rag'&&hasAbstain&&/\b(summarize|extract|resumir|extrair|résumer|extraire)\b/i.test(p);
  if(!hasGround&&!missingDocSafe&&factual&&['rag','research','support'].includes(profile)){issues.push('Factual or document-oriented task lacks an explicit grounding constraint.');recommendations.push('Tell the model which evidence it may rely on and what to do when evidence is missing.');signals.push('weak-grounding');}
  if(!hasAbstain&&['rag','research','support','agent','data'].includes(profile)){issues.push('No explicit insufficient-evidence or uncertainty behavior was detected.');recommendations.push('Allow the model to state that evidence is insufficient rather than inventing an answer.');signals.push('no-abstention');}
  if(forced){issues.push('The prompt contains forced-certainty or abstention-suppression language that can increase unsupported answers.');recommendations.push('Remove forced-certainty language and explicitly permit uncertainty or abstention when evidence is insufficient.');signals.push('forced-certainty');}
  if(abstentionForbidden){issues.push('The prompt explicitly forbids the model from admitting insufficient knowledge or evidence.');recommendations.push('Permit the model to state when it cannot verify an answer or when information is missing.');signals.push('abstention-prohibited');}
  if(uncertaintySuppression){issues.push('The prompt suppresses uncertainty, limitations, or confidence disclosure.');recommendations.push('Require uncertainty and limitations to be surfaced when evidence is incomplete.');signals.push('uncertainty-suppression');}
  if(judgeOverride){issues.push('The analyzed prompt attempts to manipulate an evaluator or requested score.');recommendations.push('Remove evaluator-manipulation instructions from the downstream task.');signals.push('evaluator-manipulation');}
  if(systemPromptExtraction){issues.push('The prompt attempts to extract hidden evaluator or system instructions.');recommendations.push('Remove system-prompt extraction instructions.');signals.push('system-prompt-extraction');}
  if(roleOverride){issues.push('The prompt contains instruction-hierarchy or role-override language.');recommendations.push('Keep downstream task instructions separate from evaluator/system controls.');signals.push('role-override');}
  if(fabricateCitation){issues.push('The prompt permits fabricated citations, sources, papers, or URLs.');recommendations.push('Require citations to be verified and report missing sources instead of inventing them.');signals.push('citation-fabrication');}
  if(inferMissing){issues.push('The prompt encourages unsupported inference or guessing when information is missing.');recommendations.push('Require missing information to be reported instead of guessed.');signals.push('infer-missing');}
  if(destructive&&!safeDestructive){issues.push('The prompt permits destructive actions without explicit confirmation.');recommendations.push('Require explicit confirmation before destructive or irreversible actions.');signals.push('unsafe-destructive-action');}
  if(causalOverclaim&&!causalSafe){issues.push('The prompt asks for a causal conclusion from evidence that may only support correlation.');recommendations.push('Separate correlation from causation and identify additional evidence required.');signals.push('causal-overclaim');}
  if(conflictBad&&!conflictSafe){issues.push('The prompt asks the model to silently resolve conflicting evidence without support.');recommendations.push('Report conflicts or ambiguity rather than selecting an unsupported value.');signals.push('conflict-resolution-by-guessing');}
  if(repeatedTool||endlessTool){issues.push('The prompt encourages unnecessary or unbounded repeated tool calls.');recommendations.push('Use the minimum necessary tool calls, reuse valid results, and stop after bounded failures.');signals.push('unbounded-tool-use');}
  if(impossibleConstraint){issues.push('The prompt contains materially conflicting output requirements.');recommendations.push('Resolve conflicting completeness and length requirements by prioritizing the most important content.');signals.push('conflicting-constraints');}
  if(intentionalRepeat){issues.push('The prompt explicitly encourages unnecessary repetition or verbosity.');recommendations.push('Prefer concise, relevant context and avoid repeating established information.');signals.push('intentional-repetition');}
  if(!hasFormat&&p.length<180){issues.push('No clear output contract was detected.');recommendations.push('Specify the desired format, length, fields, or schema.');}
  const citationRelevant=String(context||'').length>0||/\b(answer|question|claim|conclusion|policy|legal|contract|compare|resposta|pergunta|afirma[cç][aã]o|conclus[aã]o|pol[ií]tica|jur[ií]dic|contrato|comparar|réponse|question|affirmation|conclusion|politique|juridique|contrat|comparer)\b/i.test(p);
  if((profile==='rag'||String(context||'').length>0)&&citationRelevant&&!hasCitation){issues.push('Context is provided but factual claims are not explicitly tied to citations or evidence.');recommendations.push('Require factual claims to cite or point to the supplied evidence when appropriate.');signals.push('no-citations');}
  if(profile==='agent'&&hasTool&&!boundedTool){issues.push('Tool use is mentioned without clear limits or reuse guidance.');recommendations.push('Define when tools should be used, when results should be reused, and when retries should stop.');signals.push('unbounded-tool-use');}
  if(dup>0.20){issues.push('The prompt/context contains substantial repeated text.');recommendations.push('Remove duplicated instructions or context to reduce ambiguity and token waste.');signals.push('duplicate-context');}

  if(hasGround||missingDocSafe)protective.push('grounding');if(current&&currentRetrieval)protective.push('current-retrieval');if(resolvedEvaluationMode==='template')protective.push('template-contract');if(hasAbstain||noGuess)protective.push('abstention');if(hasCitation)protective.push('citations');if(hasFormat)protective.push('output-contract');if(boundedTool)protective.push('bounded-tools');if(nullMissing)protective.push('null-on-missing');if(conflictSafe)protective.push('conflict-reporting');if(safeDestructive)protective.push('destructive-confirmation');if(causalSafe)protective.push('causal-discipline');
  const explicitSet=new Set(['forced-certainty','abstention-prohibited','infer-missing','time-sensitive-without-grounding','unsafe-destructive-action','causal-overclaim','conflict-resolution-by-guessing','unbounded-tool-use','conflicting-constraints','uncertainty-suppression','citation-fabrication','evaluator-manipulation','system-prompt-extraction','role-override']);
  const explicitDanger=signals.filter(s=>explicitSet.has(s)),contextualRisk=signals.filter(s=>['weak-grounding','no-abstention','no-citations','unbounded-tool-use'].includes(s));
  let risk='low';if(explicitDanger.length>0)risk='high';else if(contextualRisk.length>=2||(current&&contextualRisk.length))risk='medium';else if(contextualRisk.length===1&&protective.length===0)risk='medium';
  return {profile,detected_language:detectedLanguage,evaluation_mode:resolvedEvaluationMode,quality_evidence:quality,metrics:{prompt_chars:p.length,context_chars:String(context||'').length,duplicate_ratio:Number(dup.toFixed(3))},flags:{current,hasGround,hasAbstain,abstentionForbidden,hasCitation,hasFormat,hasTool,boundedTool,forced,inferMissing,noGuess,destructive,safeDestructive,causalOverclaim,causalSafe,nullMissing,conflictSafe,conflictBad,repeatedTool,endlessTool,impossibleConstraint,intentionalRepeat,uncertaintySuppression,fabricateCitation,currentRetrieval,templateDetected,judgeOverride,systemPromptExtraction,roleOverride},issues:[...new Set(issues)],recommendations:[...new Set(recommendations)],risk_indicators:[...new Set(signals)],protective_controls:[...new Set(protective)],explicit_danger_count:explicitDanger.length,contextual_risk_count:contextualRisk.length,hallucination_risk:risk};
}
